---
title: "Welcome to the reconverse"
description: |
  A coherent ecosystem  of R packages for outbreak analytics.
author:
  - name: Thibaut Jombart
    url: https://thibautjombart.netlify.app/
  - name: Tim Taylor
date: 03-09-2021
output:
  distill::distill_article:
    self_contained: false
draft: false
creative_commons: CC BY
bibliography: ref.bib
citation: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Members of the [R Epidemics Consortium](https://www.repidemicsconsortium.org/)
have, for many years, been creating resources and software that could be used
to inform the response to disease outbreaks, health emergencies and
humanitarian crises. During this time, as well as providing training materials,
running workshops and having members deployed to the field to help with data
analytics, a variety of [R](https://www.r-project.org/) packages have been
created to enable analysts to quickly solve the problems they have (e.g.
[epicontacts](https://www.repidemicsconsortium.org/epicontacts/),
[epiestim](https://github.com/mrc-ide/EpiEstim),
[incidence](https://www.repidemicsconsortium.org/incidence/)).

Since the early days of RECON,  the landscape of packages for the analysis of
epidemics has grown, evolved and diversified, benefiting from feedback and
contributions from our members as well as other groups. While such organic
growth was needed and resulted in overall improvements of available tools, it
has also led to a less consistent software landscape, with several packages
overlapping or duplicating efforts, limited interoperability, and varying coding
and development standards.  Being aware that fragmented software landscapes can
be the bane of data scientists [e.g. @excoffier_computer_2006],  we
realise there is also benefit to having a coherent and composable set of
packages for users. The **reconverse** aims to address this. Much like the
[tidyverse](https://www.tidyverse.org/) is "an opinionated collection of R
packages designed for data science", the reconverse aims to be an opinionated
ecosystem of packages for Outbreak Analytics.

Completing the *reconverse* will take years, and we intend for our first steps
in this long journey to be taken carefully. However, we are not starting this
journey empty-handed. With years of experience developing packages and extensive
feedback from a wide range of users, our roadmap is unfolding with increasing
clarity. Over the coming months we will be introducing some of the packages we
view as the building blocks of the *reconverse*. In these exciting times, your
input, feedback, criticisms, requests, and contributions will be more valuable
than ever, as they will be instrumental in shaping the future of the
*reconverse* -- making it **your** reconverse.

Exciting times and challenges are ahead of us, and we are looking forward to
taking you on board this epic journey. 
